AllCops:
  NewCops: enable
  Exclude:
    - 'Guardfile'
    - 'bin/*'
    - 'spec/rails_helper\.rb'
    - 'spec/spec_helper\.rb'
    - 'spec/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples']
